on:
  push:
    tags:
      - '*'
name: Build & release
jobs:
  linux:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
        goarch: ["386", amd64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go build -ldflags '-s -w -X "github.com/axllent/golp/cmd.Version=${{ github.ref }}"'
      env:
        CGO_ENABLED: 1
    - run: tar -zcvf golp_linux_${{ matrix.goarch }}.tar.gz golp README.md LICENSE
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: golp_linux_${{ matrix.goarch }}.tar.gz
        asset_name: golp_linux_${{ matrix.goarch }}.tar.gz
        tag: ${{ github.ref }}

  darwin:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [macos-latest]
        goarch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go build -ldflags '-s -w -X "github.com/axllent/golp/cmd.Version=${{ github.ref }}"'
      env:
        CGO_ENABLED: 1
    - run: tar -zcvf golp_darwin_${{ matrix.goarch }}.tar.gz golp README.md LICENSE
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: golp_darwin_${{ matrix.goarch }}.tar.gz
        asset_name: golp_darwin_${{ matrix.goarch }}.tar.gz
        tag: ${{ github.ref }}

  windows:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [windows-latest]
        goarch: ["386", amd64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go build -ldflags '-s -w -extldflags -static -X "github.com/axllent/golp/cmd.Version=${{ github.ref }}"'
      env:
        CGO_ENABLED: 1
    - run: go build -ldflags "-s -w" .
    - name: Compress zip files
      uses: papeloto/action-zip@v1
      with:
        files: golp.exe README.md LICENSE
        dest: golp_windows_${{ matrix.goarch }}.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: golp_windows_${{ matrix.goarch }}.zip
        asset_name: golp_windows_${{ matrix.goarch }}.zip
        tag: ${{ github.ref }}
