on: [push, pull_request]
name: Test
jobs:
  ubuntu-test:
    strategy:
      matrix:
        go-version: [1.18.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        goarch: ["386", amd64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go build -ldflags "-s -w" .

  darwin-test:
    strategy:
      matrix:
        go-version: [1.18.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]
        goarch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: CGO_ENABLED=1 go build -ldflags "-s -w" .
